/**
 * botDecks.js — Pre-built Commander Precon Decklists
 * Organized by bracket level (1-4).
 * Each deck: { name, commander, cards: ['Card Name', ...] (99 cards + commander = 100) }
 *
 * These are based on real MTG Commander precon decks, slightly simplified
 * for reliability with Scryfall name lookups.
 */

const BOT_DECKS = {
  1: [
    // ── Bracket 1: Casual precon-level decks ──
    {
      name: "Growing Threat",
      commander: "Toxrill, the Corrosive",
      bracket: 1,
      cards: [
        "Toxrill, the Corrosive",
        "Bladebrand", "Body Count", "Curtains' Call", "Dredge the Mire",
        "Feed the Swarm", "Go for the Throat", "Murder", "Pact of the Serpent",
        "Putrefy", "Sever the Bloodline", "Tragic Slip",
        "Deadly Rollick", "Dismember",
        "Aetherize", "Counterspell", "Cyclonic Rift", "Didn't Say Please",
        "Mana Drain", "Negate", "Propaganda",
        "Phyrexian Arena", "Revel in Riches", "Search for Azcanta",
        "Overseer of the Damned",
        "Altar of Dementia", "Arcane Signet", "Commander's Sphere",
        "Dimir Signet", "Sol Ring", "Swiftfoot Boots", "Thought Vessel",
        "Strionic Resonator",
        "Bojuka Bog", "Command Tower", "Darkwater Catacombs",
        "Dimir Aqueduct", "Drowned Catacomb", "Evolving Wilds",
        "Fetid Pools", "Morphic Pool",
        "Sunken Hollow", "Tainted Isle", "Underground River",
        "Watery Grave",
        "Island", "Island", "Island", "Island", "Island", "Island", "Island", "Island",
        "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp",
        "Brine Elemental", "Deep-Sea Kraken", "Kaervek the Merciless",
        "Lurking Predators", "Migratory Route",
        "Slippery Bogbonder", "Voracious Greatshark",
        "Champion of Wits", "Eternal Witness",
        "Baleful Strix", "Sepulchral Primordial",
        "Grave Titan", "Noxious Gearhulk", "Phyrexian Delver",
        "Sheoldred, Whispering One",
        "Diluvian Primordial",
        "Body Launderer", "Cemetery Puca", "Consuming Aberration",
        "Dauthi Voidwalker",
        "Ghostly Pilferer",
        "Manor Skeleton",
        "Nightshade Stinger",
        "Opposition Agent",
        "Phyrexian Metamorph",
        "Ravenous Chupacabra",
        "Void Beckoner",
        "Witchbane Orb",
      ],
    },

    {
      name: "Heads I Win, Tails You Lose",
      commander: "Prosper, Tome-Bound",
      bracket: 1,
      cards: [
        "Prosper, Tome-Bound",
        "Chaos Warp", "Chandra's Ignition", "Crackle with Power", "Dark Ritual",
        "Demonic Tutor", "Feed the Swarm", "Gamble",
        "Jeska's Will", "Mana Geyser", "Pyroclasm", "Reckless Abandon",
        "Seize the Spotlight", "Shadows of the Past",
        "Arcane Signet", "Cursed Mirror", "Dimir Signet",
        "Greed", "Marchesa's Decree", "Midnight Clock",
        "Rakdos Signet", "Sol Ring",
        "Swiftfoot Boots", "Talisman of Conviction",
        "Thought Vessel",
        "Bolas's Citadel",
        "Command Tower", "Exotic Orchard", "Foreboding Ruins",
        "Luxury Suite", "Rakdos Carnarium",
        "Sulfurous Springs", "Tainted Peak", "Temple of Malice",
        "Mountain", "Mountain", "Mountain", "Mountain", "Mountain", "Mountain", "Mountain", "Mountain",
        "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp",
        "Aetherflux Reservoir",
        "Bloodchief Ascension",
        "Chandra, Torch of Defiance",
        "Dauthi Voidwalker",
        "Dictate of Erebos",
        "Elturel Survivors",
        "Etali, Primal Storm",
        "Heartless Pillage",
        "Hellkite Tyrant",
        "Ignite the Future",
        "Immersturm Predator",
        "Izzet Chemister",
        "Kaervek the Merciless",
        "Light Up the Stage",
        "Loot Dispute",
        "Pillage",
        "Popular Entertainer",
        "Professional Face-Breaker",
        "Rakdos Charm",
        "Revel in Riches",
        "Scion of Darkness",
        "Sedgemoor Witch",
        "Shapesharer",
        "Shiny Impetus",
        "Stolen Strategy",
        "Sword of the Animist",
        "Tevesh Szat, Doom of Fools",
        "Thunderiron Slug",
        "Torment of Hailfire",
        "Valki, God of Lies",
        "Void Beckoner",
        "War Room",
      ],
    },
  ],

  2: [
    {
      name: "Buckle Up",
      commander: "Shorikai, Genesis Engine",
      bracket: 2,
      cards: [
        "Shorikai, Genesis Engine",
        "Coastal Bulwark", "Cultivator's Caravan", "Dispatch",
        "Hammer of Purphoros",
        "Jhoira's Familiar", "Kindred Discovery",
        "Master Transmuter",
        "Padeem, Consul of Innovation",
        "Pugnacious Hammerskull",
        "Soul of New Phyrexia",
        "Thoughtcast",
        "Trophy Mage", "Weatherlight",
        "Whir of Invention",
        "Arcane Signet",
        "Azorius Signet",
        "Batterskull",
        "Colossus Hammer",
        "Commander's Sphere",
        "Darksteel Citadel",
        "Fellwar Stone",
        "Foundry Inspector",
        "Glacial Fortress",
        "Lightning Greaves",
        "Mechanized Production",
        "Mirrormade",
        "Mystic Forge",
        "Open the Vaults",
        "Ornithopter of Paradise",
        "Razor Golem",
        "Sculpting Steel",
        "Semblance Anvil",
        "Skullclamp",
        "Sol Ring",
        "Spire of Industry",
        "Steel Overseer",
        "Swiftfoot Boots",
        "Talisman of Progress",
        "The Immortal Sun",
        "Thought Vessel",
        "Command Tower",
        "Deserted Beach",
        "Eiganjo Castle",
        "Emeria, the Sky Ruin",
        "Hallowed Fountain",
        "Island", "Island", "Island", "Island", "Island", "Island", "Island", "Island", "Island",
        "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains",
        "Port Town",
        "Prairie Stream",
        "Seachrome Coast",
        "Tranquil Cove",
        "Aethersphere Harvester",
        "Aetherstorm Roc",
        "Alela, Artful Provocateur",
        "Azorius Arrester",
        "Blinkmoth Nexus",
        "Chief of the Foundry",
        "Cloudblazer",
        "Darksteel Colossus",
        "Digsite Engineer",
        "Emry, Lurker of the Loch",
        "Esior, Wardwing Familiar",
        "Etched Champion",
        "Filigree Attendant",
        "Metalwork Colossus",
        "Myr Battlesphere",
        "Platinum Angel",
        "Raff Capashen, Ship's Mage",
        "Shimmer Dragon",
        "Sram, Senior Edificer",
        "Thopter Assembly",
        "Traxos, Scourge of Kroog",
      ],
    },

    {
      name: "Draconic Dissent",
      commander: "Firkraag, Cunning Instigator",
      bracket: 2,
      cards: [
        "Firkraag, Cunning Instigator",
        "Arcane Signet", "Bident of Thassa", "Chaos Warp", "Chromatic Lantern",
        "Cormela, Glamour Thief",
        "Curse of Opulence",
        "Cyclonic Rift",
        "Disdainful Stroke",
        "Domineering Will",
        "Faithless Looting",
        "Faithless Salvaging",
        "Feed the Swarm",
        "Heartless Pillage",
        "Into the Fire",
        "Invoker of the Depths",
        "Jeska's Will",
        "Kediss, Emberclaw Familiar",
        "Kraum, Ludevic's Opus",
        "Lorehold Command",
        "Ludevic, Necro-Alchemist",
        "Manaform Hellkite",
        "Melek, Izzet Paragon",
        "Mnemonic Deluge",
        "Niv-Mizzet, Parun",
        "Opportunist's Gambit",
        "Ral Zarek",
        "Refuse // Cooperate",
        "Rionya, Fire Dancer",
        "Izzet Signet",
        "Ruination Rioter",
        "Scion of Draco",
        "Shiny Impetus",
        "Sol Ring",
        "Spark Double",
        "Swiftfoot Boots",
        "Talrand, Sky Summoner",
        "The Locust God",
        "Thought Vessel",
        "Thundering Raiju",
        "Tidal Barracuda",
        "Tyrant's Familiar",
        "Warchief Giant",
        "Young Pyromancer",
        "Command Tower",
        "Exotic Orchard",
        "Fiery Islet",
        "Highland Lake",
        "Island", "Island", "Island", "Island", "Island", "Island", "Island", "Island",
        "Mountain", "Mountain", "Mountain", "Mountain", "Mountain", "Mountain", "Mountain", "Mountain",
        "Prismari Campus",
        "Shivan Reef",
        "Spirebluff Canal",
        "Steam Vents",
        "Sulfur Falls",
        "Temple of Epiphany",
        "Wandering Fumarole",
      ],
    },
  ],

  3: [
    {
      name: "Corrupting Influence",
      commander: "Breena, the Demagogue",
      bracket: 3,
      cards: [
        "Breena, the Demagogue",
        "Arcane Signet", "Bennie Bracks, Zoologist",
        "Black Market Connections",
        "Bloodchief Ascension",
        "Bloodforged Battle-Axe",
        "Bone Sabres",
        "Chainer, Nightmare Adept",
        "Champion of Lambholt",
        "Cliffhaven Vampire",
        "Curator's Ward",
        "Danitha Capashen, Paragon",
        "Dark Impostor",
        "Deadly Wanderings",
        "Decree of Pain",
        "Deep Gnome Terramancer",
        "Drana, Liberator of Malakir",
        "Duelist's Heritage",
        "Embellished Plate",
        "Essence Drain",
        "Ethereal Armor",
        "Expropriate",
        "Fell Stinger",
        "Fireshrieker",
        "Flowering of the White Tree",
        "Garruk's Uprising",
        "Grim Hireling",
        "Inkshield",
        "Inquisitorial Rosette",
        "Keeper of Secrets",
        "Lifeblood Hydra",
        "Light of Day",
        "Loran of the Third Path",
        "Loran's Escape",
        "Master of Cruelties",
        "Orzhov Signet",
        "Plunge into Darkness",
        "Propaganda",
        "Prowler's Helm",
        "Rakdos Signet",
        "Reconnaissance",
        "Rogue's Passage",
        "Sage's Row Denizen",
        "Shadows of the Past",
        "Silverblade Paladin",
        "Sol Ring",
        "Strionic Resonator",
        "Swiftfoot Boots",
        "Talisman of Hierarchy",
        "Talisman of Indulgence",
        "Thought Vessel",
        "Together Forever",
        "Waste Not",
        "Command Tower", "Caves of Koilos", "Fetid Heath",
        "Godless Shrine", "Isolated Chapel", "Orzhov Basilica",
        "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains",
        "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp",
        "Tainted Field", "Temple of Silence",
        "Vault of the Archangel",
        "Astarion, the Decadent",
        "Felisa, Fang of Silverquill",
        "Lae'zel, Vlaakith's Champion",
        "Osgir, the Reconstructor",
        "Prava of the Steel Legion",
        "Tymna the Weaver",
        "Alharu, Solemn Ritualist",
        "Burakos, Party Leader",
        "Minthara, Merciless Soul",
        "Tormod, the Desecrator",
        "Vela the Night-Clad",
        "White Plume Adventurer",
      ],
    },

    {
      name: "Shards of Darkness",
      commander: "Wilhelt, the Rotcleaver",
      bracket: 3,
      cards: [
        "Wilhelt, the Rotcleaver",
        "Arcane Signet", "Ashnod's Altar",
        "Binding the Old Gods",
        "Bladestitched Skaab",
        "Blood for Bones",
        "Brainstorm",
        "Cemetery Reaper",
        "Curse of Disturbance",
        "Curse of Shallow Graves",
        "Cyclonic Rift",
        "Dark Salvation",
        "Death Baron",
        "Dimir Signet",
        "Distant Melody",
        "Doomed Dissenter",
        "Dread Return",
        "Endless Ranks of the Dead",
        "Fleshbag Marauder",
        "Forgotten Creation",
        "Geralf's Messenger",
        "Gisa and Geralf",
        "Gisa, Glorious Resurrector",
        "God-Eternal Bontu",
        "Grave Titan",
        "Graveyard Marshal",
        "Headless Rider",
        "Heavenly Blademaster",
        "Icon of Ancestry",
        "Josu Vess, Lich Knight",
        "Labyrinth Raptor",
        "Lim-Dul the Necromancer",
        "Living Death",
        "Lord of the Accursed",
        "Midnight Reaper",
        "Nemesis of Mortals",
        "Phenax, God of Deception",
        "Phyrexian Altar",
        "Psychic Corrosion",
        "Rally the Ranks",
        "Rooftop Storm",
        "Siphon Flesh",
        "Skullclamp",
        "Slaughter Specialist",
        "Sol Ring",
        "Swiftfoot Boots",
        "Talisman of Dominance",
        "Thought Vessel",
        "Tormod, the Desecrator",
        "Undead Augur",
        "Undead Butler",
        "Unholy Grotto",
        "Vengeful Dead",
        "Vesperlark",
        "Victimize",
        "Wight of Precinct Six",
        "Zombie Master",
        "Command Tower", "Darkwater Catacombs", "Drowned Catacomb",
        "Fetid Pools", "Island", "Island", "Island", "Island", "Island", "Island", "Island", "Island",
        "Morphic Pool", "Sunken Hollow", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp", "Swamp",
        "Swamp", "Swamp", "Tainted Isle", "Underground River", "Watery Grave",
        "Blighted Fen",
      ],
    },
  ],

  4: [
    {
      name: "Atraxa Proliferate",
      commander: "Atraxa, Praetors' Voice",
      bracket: 4,
      cards: [
        "Atraxa, Praetors' Voice",
        "Abzan Charm", "Arcane Signet",
        "Astral Cornucopia",
        "Blighted Agent",
        "Bloated Contaminator",
        "Body of Research",
        "Bred for the Hunt",
        "Caress of Phyrexia",
        "Contagion Clasp",
        "Contagion Engine",
        "Contentious Plan",
        "Core Prowler",
        "Crystalline Crawler",
        "Darkwater Catacombs",
        "Deepglow Skate",
        "Doubling Season",
        "Duskshell Crawler",
        "Exotic Orchard",
        "Evolution Sage",
        "Everflowing Chalice",
        "Experiment One",
        "Farewell",
        "Flux Channeler",
        "Font of Agonies",
        "Force of Vigor",
        "Grateful Apparition",
        "Grim Affliction",
        "Hammer of Purphoros",
        "Inexorable Tide",
        "Jhoira's Familiar",
        "Kodama's Reach",
        "Lands",
        "Lae'zel, Vlaakith's Champion",
        "Lights Out",
        "Luxior, Giada's Gift",
        "Majesty of Zhalfir",
        "Manifold Key",
        "Merfolk Skydiver",
        "Migloz, Maze Crusher",
        "Mirrodin Besieged",
        "Mondrak, Glory Dominus",
        "Nesting Grounds",
        "Nissa, Voice of Zendikar",
        "Norn's Choirmaster",
        "Ob Nixilis, the Fallen",
        "Ooze Flux",
        "Open the Gates",
        "Ordeal of Heliod",
        "Pentax Prism",
        "Perennial Behemoth",
        "Plaguemaw Beast",
        "Plains", "Plains",
        "Pollenbright Druid",
        "Prismari Command",
        "Retribution of the Meek",
        "Sacrifice",
        "Satyr Wayfinder",
        "Scale the Heights",
        "Smell Fear",
        "Sol Ring",
        "Species Specialist",
        "Spike Weaver",
        "Starfield Mystic",
        "Surrak Dragonclaw",
        "Swiftfoot Boots",
        "Talisman of Dominance", "Talisman of Progress", "Talisman of Unity",
        "Tangle Wire",
        "Thought Vessel",
        "Thundering Raiju",
        "Tyrant's Familiar",
        "Undergrowth Stadium",
        "Verdurous Gearhulk",
        "Vivid Creek", "Vivid Grove", "Vivid Marsh", "Vivid Meadow",
        "Void Shatter",
        "Winding Constrictor",
        "Zegana, Utopian Speaker",
        "Command Tower",
        "Forest", "Forest", "Forest", "Forest",
        "Island", "Island", "Island",
        "Plains",
        "Swamp",
        "Llanowar Wastes", "Underground River", "Brushland",
        "Caves of Koilos",
        "Murmuring Bosk",
        "Reflecting Pool",
        "Overgrown Tomb", "Temple Garden", "Watery Grave", "Hallowed Fountain",
        "Breeding Pool", "Godless Shrine",
      ],
    },

    {
      name: "Light-Paws Voltron",
      commander: "Light-Paws, Emperor's Voice",
      bracket: 4,
      cards: [
        "Light-Paws, Emperor's Voice",
        "Ancestral Mask", "Arcane Signet",
        "Armored Ascension", "Auramancer",
        "Aura of Silence",
        "Bequeathal", "Brightcloak Mentor",
        "Cartouche of Solidarity",
        "Celestial Mantle",
        "Cloak and Dagger", "Commander's Sphere",
        "Danitha Capashen, Paragon",
        "Duelist's Heritage",
        "Elspeth, Sun's Nemesis",
        "Enchanted Evening",
        "Ethereal Armor",
        "Etchings of the Chosen",
        "Everwatching Threshold",
        "Feather, the Redeemed",
        "Flickering Ward",
        "Gift of Immortality",
        "Gilded Light",
        "Griffin Aerie",
        "Hanna, Ship's Navigator",
        "Heliod, Sun-Crowned",
        "Hero of Iroas",
        "Hyena Umbra",
        "Idyllic Tutor",
        "Indomitable Will",
        "Inspiring Unicorn",
        "Karametra's Blessing",
        "Kor Spiritdancer",
        "Lotus Petal",
        "Luminarch Ascension",
        "Mesa Enchantress",
        "Mistveil Plains",
        "Monk Idealist",
        "Nettlecyst",
        "Open the Armory",
        "Ordeal of Heliod",
        "Paladin Class",
        "Pariah",
        "Pegasus Guardian",
        "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains",
        "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains", "Plains",
        "Plains", "Plains", "Plains", "Plains",
        "Plea for Guidance",
        "Purity",
        "Rasaad yn Bashir",
        "Reconnaissance",
        "Replenish",
        "Retether",
        "Sage's Reverie",
        "Serra's Embrace",
        "Shielded by Faith",
        "Sigarda's Splendor",
        "Silhana Ledgewalker",
        "Sol Ring",
        "Squire's Devotion",
        "Stasis Snare",
        "Steel of the Godhead",
        "Swiftfoot Boots",
        "Swords to Plowshares",
        "Talisman of Progress",
        "Three Dreams",
        "Unquestioned Authority",
        "Utopia Sprawl",
        "Vessels of Nascency",
        "Vigilance",
        "Winds of Rath",
        "Command Tower", "Emeria, the Sky Ruin",
        "Mistveil Plains",
        "Secluded Steppe",
      ],
    },
  ],
};

/**
 * Get a random selection of 3 distinct bot decks for the given bracket level.
 * Falls back to lower brackets if not enough decks at the given level.
 */
function getRandomBotDecks(bracketLevel) {
  const allDecks = [];

  // Collect decks at and below the selected bracket
  for (let b = bracketLevel; b >= 1; b--) {
    if (BOT_DECKS[b]) allDecks.push(...BOT_DECKS[b]);
    if (allDecks.length >= 3) break;
  }

  // Shuffle and take 3
  const shuffled = [...allDecks].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 3);
}
